export default function (country) {
    
    const data = {
        AE: "United Arab Emirates",
        AM: "Armenia",
        AR: "Argentina",
        AT: "Austria",
        AU: "Australia",
        AZ: "Azerbaijan",
        BG: "Bulgaria",
        BE: "Belgium",
        BH: "Bahrain",
        BO: "Bolivia",
        BR: "Brazil",
        BW: "Botswana",
        BY: "Belarus",
        CA: "Canada",
        CH: "Switzerland",
        CL: "Chile",
        CN: "China",
        CO: "Colombia",
        CR: "Costa Rica",
        CZ: "Czech Republic",
        DE: "Germany",
        DK: "Denmark",
        DO: "Dominican Republic",
        EC: "Ecuador",
        EE: "Estonia",
        EG: "Egypt",
        ES: "Spain",
        EG: "Ethiopia",
        FI: "Finland",
        FR: "France",
        GB: "United Kingdom",
        GH: "Ghana",
        GR: "Greece",
        GT: "Guatemala",
        HN: "Honduras",
        HR: "Croatia",
        HU: "Hungary",
        ID: "Indonesia",
        IE: "Ireland",
        IL: "Israel",
        IN: "India",
        IQ: "Iraq",
        IT: "Italy",
        JO: "Jordan",
        JM: "Jamaica",
        JP: "Japan",
        KE: "Kenya",
        KG: "Kyrgyzstan",
        KR: "Korea",
        KW: "Kuwait",
        KZ: "Kazakhstan",
        LB: "Lebanon",
        LT: "Lithuania",
        LV: "Latvia",
        LU: "Luxembourg",
        MX: "Mexico",
        MY: "Malaysia",
        MZ: "Mozambique",
        NA: "Namibia",
        NG: "Nigeria",
        NI: "Nicaragua",
        NL: "Netherlands",
        NO: "Norway",
        NZ: "New Zealand",
        OM: "Oman",
        PA: "Panama",
        PE: "Peru",
        PH: "Philippines",
        PK: "Pakistan",
        PL: "Poland",
        PT: "Portugal",
        PY: "Paraguay",
        QA: "Qatar",
        RO: "Romania",
        RS: "Serbia",
        RU: "Russian Federation",
        SA: "Saudi Arabia",
        SE: "Sweden",
        SG: "Singapore",
        SK: "Slovakia",
        SI: "Slovenia",
        SV: "El Salvador",
        TH: "Thailand",
        TJ: "Tajikistan",
        TM: "Turkmenistan",
        TR: "Turkey",
        TZ: "Tanzania",
        TW: "Taiwan",
        TT: "Trinidad and Tobago",
        UG: "Uganda",
        UA: "Ukraine",
        US: "United States",
        UY: "Uruguay",
        UZ: "Uzbekistan",
        VE: "Venezuela",
        VN: "Vietnam",
        YE: "Yemen",
        ZA: "South Africa",
        ZW: "Zimbabwe",
        HK: "Hong Kong",
        LK: "Sri Lanka",
        
        null: 'United Kingdom'
    }

    return(data[country]);

}