// This common config file is used in FormComponent tool
var __FC_commonConfig__ = {

    // 1)
    existingDivisions: {
        AAD: 'AAD - Automotive Aftermarket Division',
        AASD: 'AASD - Automotive & Aerospace Solutions Division',
        AdMD: 'AdMD - Advanced Material Division',
        ASD: 'ASD - Abrasive Systems Division',
        CBS: 'CBS - Consumer Business Sponsored',
        CHC: 'CHC - Consumer Health Care Division',
        CHIM: 'CHIM - Construction & Home Improvement Division',
        CMSD: 'CMSD - Closure and Masking Systems Division',
        CORP: 'CORP - Corporate',
        CSD: 'CSD - Commercial Solutions Division',
        DDSD: 'DDSD - Drug Delivery Systems',
        DMSD: 'DMSD - Display Materials & Systems Division',
        EAR: 'EAR - Aearo Technologies LLC',
        EMD: 'EMD - Electrical Markets Division',
        EMSD: 'EMSD - Electronics Materials Solutions Division',
        FSD: 'FSD - Food Safety',
        GOV: 'GOV - Government Markets',
        HCD: 'HCD - Home Care Division',
        HIS: 'HIS - Health Information Systems',
        IATD: 'IATD - Industrial Adhesives and Tapes Division',
        IMPD: 'IMPD - Industrial Mineral Products Division',
        IPD: 'IPD - Infection Prevention Division',
        ISMC: 'ISMC - Industrial and Safety Market Center',
        LITT: 'LITT - Littmann Stethoscopes',
        MEG: "MEG - Meguiar's",
        MMC: 'MMC - Medical Markets Center',
        MMT: 'MMT - Medical Materials &amp; Technologies',
        MSD: 'MSD - Medical Solutions Division',
        MULT: 'MULTI - Multiple Divisions',
        OCSD: 'OCSD - Oral Care Solutions Division',
        PSD: 'PSD - Personal Safety Division',
        SOSD: 'SOSD - Stationery & Office Supplies Division',
        SPSD: 'SPSD - Separation and Purification Science Division',
        TSD: 'TSD - Transportation Safety Division',
        VAS: 'VAS - Visual Attention Services',
        // Relates to ASD currently
        TMC: 'ASD - Abrasive Systems Division',
    },

// 2)
// If you have in fields configuration file something new (Standard ones: CA, Basic), please reflect the same value for the relevant division here:
    leadGenTypesExisting: {
        AAD: ['CA', 'Basic',],
        AASD: ['CA', 'Basic',],
        AdMD: ['CA', 'Basic',],
        ASD: ['CA', 'Basic', 'TMC_Basic', 'TMC_CA'],
        CBS: ['CA', 'Basic',],
        CHC: ['CA', 'Basic',],
        CHIM: ['CA', 'Basic',],
        CMSD: ['CA', 'Basic',],
        CORP: ['CA', 'Basic',],
        CSD: ['CA', 'Basic',],
        DDSD: ['CA', 'Basic',],
        DMSD: ['CA', 'Basic',],
        EAR: ['CA', 'Basic',],
        EMD: ['CA', 'Basic',],
        EMSD: ['CA', 'Basic',],
        FSD: ['CA', 'Basic',],
        GOV: ['CA', 'Basic',],
        HCD: ['CA', 'Basic',],
        HIS: ['CA', 'Basic',],
        IATD: ['CA', 'Basic',],
        IMPD: ['CA', 'Basic',],
        IPD: ['CA', 'Basic',],
        ISMC: ['CA', 'Basic',],
        LITT: ['CA', 'Basic',],
        MEG: ['CA', 'Basic',],
        MMC: ['CA', 'Basic',],
        MMT: ['CA', 'Basic',],
        MSD: ['CA', 'Basic',],
        MULT: ['CA', 'Basic',],
        OCSD: ['CA', 'Basic',],
        PSD: ['CA', 'Basic',],
        SOSD: ['CA', 'Basic',],
        SPSD: ['CA', 'Basic',],
        TSD: ['CA', 'Basic',],
        VAS: ['CA', 'Basic',],       
    },

    // 3)
    //All mql form types must be reflected here
    mqlFormTypes: ['SAM', 'DEM', 'ASK', 'CON', 'LAR'],

    // 4)
    countries: {
        AE: "United Arab Emirates",
        AM: "Armenia",
        AR: "Argentina",
        AT: "Austria",
        AU: "Australia",
        AZ: "Azerbaijan",
        BG: "Bulgaria",
        BE: "Belgium",
        BH: "Bahrain",
        BO: "Bolivia",
        BR: "Brazil",
        BW: "Botswana",
        BY: "Belarus",
        CA: "Canada",
        CH: "Switzerland",
        CL: "Chile",
        CN: "China",
        CO: "Colombia",
        CR: "Costa Rica",
        CZ: "Czech Republic",
        DE: "Germany",
        DK: "Denmark",
        DO: "Dominican Republic",
        EC: "Ecuador",
        EE: "Estonia",
        EG: "Egypt",
        ES: "Spain",
        EG: "Ethiopia",
        FI: "Finland",
        FR: "France",
        GB: "United Kingdom",
        GH: "Ghana",
        GR: "Greece",
        GT: "Guatemala",
        HN: "Honduras",
        HR: "Croatia",
        HU: "Hungary",
        ID: "Indonesia",
        IE: "Ireland",
        IL: "Israel",
        IN: "India",
        IQ: "Iraq",
        IT: "Italy",
        JO: "Jordan",
        JM: "Jamaica",
        JP: "Japan",
        KE: "Kenya",
        KG: "Kyrgyzstan",
        KR: "Korea",
        KW: "Kuwait",
        KZ: "Kazakhstan",
        LB: "Lebanon",
        LT: "Lithuania",
        LV: "Latvia",
        LU: "Luxembourg",
        MX: "Mexico",
        MY: "Malaysia",
        MZ: "Mozambique",
        NA: "Namibia",
        NG: "Nigeria",
        NI: "Nicaragua",
        NL: "Netherlands",
        NO: "Norway",
        NZ: "New Zealand",
        OM: "Oman",
        PA: "Panama",
        PE: "Peru",
        PH: "Philippines",
        PK: "Pakistan",
        PL: "Poland",
        PT: "Portugal",
        PY: "Paraguay",
        QA: "Qatar",
        RO: "Romania",
        RS: "Serbia",
        RU: "Russian Federation",
        SA: "Saudi Arabia",
        SE: "Sweden",
        SG: "Singapore",
        SK: "Slovakia",
        SI: "Slovenia",
        SV: "El Salvador",
        TH: "Thailand",
        TJ: "Tajikistan",
        TM: "Turkmenistan",
        TR: "Turkey",
        TZ: "Tanzania",
        TW: "Taiwan",
        TT: "Trinidad and Tobago",
        UG: "Uganda",
        UA: "Ukraine",
        US: "United States",
        UY: "Uruguay",
        UZ: "Uzbekistan",
        VE: "Venezuela",
        VN: "Vietnam",
        YE: "Yemen",
        ZA: "South Africa",
        ZW: "Zimbabwe",
        HK: "Hong Kong",
        LK: "Sri Lanka",
        //pls don't remove null 
        null: 'United Kingdom'
    },

    // 5) 
    languages: {
        ar:'Arabic',
        bg:'Bulgarian',       
        hr:'Croatian',
        cs:'Czech',
        da:'Danish',
        nl:'Dutch',
        en:'English',
        et:'Estonian',
        fi:'Finnish',
        fr:'French',
        de:'German',
        el:'Greek',
        iw:'Hebrew',
        hu:'Hungarian',
        it:'Italian',        
        lv:'Latvian',
        lt:'Lithuanian',
        no:'Norwegian',
        pl:'Polish',
        pt:'Portuguese',
        ro:'Romanian',
        ru:'Russian',
        sr:'Serbian',
        sk:'Slovakian',
        sl:'Slovenian',
        es:'Spanish',
        sv:'Swedish',       
        tr:'Turkish',
        uk:'Ukrainian',
        //pls don't remove null 
        null: 'English'
    },

    // 6) SMP fields' configuration templates
    smpRouting: {
        EMSD: 'https://images.engage.3m.com/Web/3MCompanyGlobal/%7Bb8c535bc-4579-47b4-a485-ce507735b8ae%7D_smp-emsd-data.js',  
        ASD: 'https://images.engage.3m.com/Web/3MCompanyGlobal/%7b2204e807-b1fc-48f9-9125-6ef8b6e975ae%7d_smp-asd-data.js',     
        
    },

    // 7) Non-SMP configuration templates
    nonSMP_baseTemplate: 'https://images.engage.3m.com/Web/3MCompanyGlobal/%7B6245aff6-8ec8-4952-b531-562bfdc4d998%7D_test-nosmp-base-data.js',

    // 8) All language configuration templates
    langRouting: {
        Arabic: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{5e7758fe-04af-46c7-8539-4fcc20fc92a2}_language-data-ar.js.js',       
        Bulgarian: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{a8bd3b35-0670-4cde-99da-4ce6acd9c9a1}_language-data-bg.js',
        Croatian: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{d81cafa0-938d-4062-b8b4-fbd41e98836e}_language-data-hr.js',
        Czech: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{4ad7d5cd-17a7-4378-8a1a-966670a52270}_language-data-cs.js',
        Danish: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{aae3a5b9-a25f-4532-bbc4-4c6197d39431}_language-data-da.js',
        Dutch: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{87641d1c-faf4-44cf-b3f4-1377b2b55d51}_language-data-nl.js',
        English: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{543cc81d-516e-4fd9-a565-7f7d4d5ef6f9}_language-data-en.js',
        Estonian: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{3d224f5b-76c9-4be3-b136-259ab65c2abc}_language-data-et.js',
        Finnish: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{eadb416c-5153-4b87-9215-6be7becc55a2}_language-data-fi.js',
        French: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{e347b50a-a48b-4556-997c-c6a411b6551c}_language-data-fr.js',
        German: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{59fba2ec-eb80-415d-85f5-e549c218a1fe}_language-data-de.js',
        Greek: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{e4cff3ec-b0a7-499b-ac29-a0a934ba403f}_language-data-el.js',
        Hebrew: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{aafaf0bb-19da-4a44-8108-7ca1a9c2ae87}_language-data-iw.js',
        Hungarian: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{15809426-16a1-4bf3-90d8-82eee2ec4d4b}_language-data-hu.js',
        Italian: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{c4ece686-8662-4755-b6de-480fc8d078d5}_language-data-it.js',
        Latvian: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{a3c34d4f-c8ed-42c9-b669-33fc9da8f1e3}_language-data-lv.js',
        Lithuanian: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{adbb416d-b5d3-4caf-9b1d-298344916be0}_language-data-lt.js',
        Norwegian: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{47cb46af-709f-4b03-a76c-552744672568}_language-data-no.js',
        Polish: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{d2561afb-fe13-428e-b907-6af9ce2c05e6}_language-data-pl.js',
        Portuguese: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{2c261101-fd15-4d50-8793-1d5ce64b488a}_language-data-pt.js',
        Romanian: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{59110a15-de93-4d19-bf92-03e84a0815fe}_language-data-ro.js',
        Serbian: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{1619a415-f5ec-4ec0-9747-b9a0dafdd48c}_language-data-sr.js',
        Slovakian: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{3d537998-c514-4fbb-be00-33911c4697ba}_language-data-sk.js',
        Slovenian: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{fb338cfd-65b5-4359-93f7-dabcad99ff9c}_language-data-sl.js',
        Spanish: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{6a67ca63-14ea-40f9-9644-f5ee3448eac3}_language-data-es.js',
        Swedish: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{853a9287-873c-48f4-84d7-d8a8630f1b41}_language-data-sv.js',
        Turkish: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{e8e95aaf-1535-4a35-8870-9d921d0a1107}_language-data-tr.js',
        Ukrainian: 'https://images.engage.3m.com/Web/3MCompanyGlobal/{b90aa56f-150f-4ea5-8ac0-77e3887b4c38}_language-data-uk.js',
    },

    // 9) 
    additionalFieldsConfig: [],

    // 10) Global Forms script, kungfu modules, etc...
    scriptsAndModules3M: {
        // String only
        loadModule1: 'kungfu/EmailForm/EmailOptions',

        // Array of Strings
        scripts3M: ["//www.3m.com/3m_theme_assets/themes/3MTheme/assets/scripts/build/kungfu/Eloqua/eloquaCountries.js",
                    "//www.3m.com/3m_theme_assets/themes/3MTheme/assets/scripts/build/kungfu/Eloqua/eloquaConsent.js",
                    "//www.3m.com/3m_theme_assets/themes/3MTheme/assets/scripts/build/kungfu/Eloqua/eloquaLanguages.js",
                    "//www.3m.com/3m_theme_assets/themes/3MTheme/assets/scripts/build/kungfu/Eloqua/eloquaStates.js",
                    ],

        // Array of Strings
        restModules: ['kungfu/Eloqua/globalFormsModule'],
        
        // Array of Strings
        // You can add here a new scripts paths to be loaded
        restScripts: [],

    },    
}