__globScopeLanguageTemplate__ = {
    optionalText: 'İsteğe bağlı',
    statement: "Aksi belirtilmediği takdirde tüm alanların doldurulması zorunludur",
    submit: "Gönder",
    defaultSelect: "Birini seçiniz",
    submissionSuccess_1: "Teşekkür ederiz. ",
    submissionSuccess_2: "Formunuz başarıyla gönderildi",
    submissionError_1: "Özür dileriz. ",
    submissionError_2: "Gönderilirken bir hata oluştu. Lütfen daha sonra tekrar deneyin",


    emailAddress: {
        label: "İş E-posta Adresi",
        errMessage: "Bir iş e-posta adresi girin",
        emailMessage: "E-posta adresi doğru biçimde değil/Geçerli bir e-posta adresi gerekiyor",
    },

    firstName: {
        label: "Adınız",
        errMessage: "Adınız",
    },

    lastName: {
        label: "Soyadınız",
        errMessage: "Soyadınız",
    },

    salutation: {
        label: "Unvan",
        errMessage: "Bu alan zorunludur",
        options: [
            ['Mr.', 'Bay '],
            ['Mrs.', 'Bayan '],
            // ['Ms.','Ms. '],
            //['Miss.','Miss. '],
            //  ['Dr.','Dr. '],
            //['Dra','Dra '],
            // ['Prof.','Prof. '],
            // ['Profa','Profa '],
        ]
    },

    company: {
        label: "Şirket",
        errMessage: "Şirketinizin adını girin",
    },

    city: {
        label: "Şehir",
        errMessage: "İlçe",
    },

    zipPostal: {
        label: "Posta Kodu",
        errMessage: "Posta Kodu",
    },

    busPhone: {
        label: "İş telefon numarası",
        errMessage: "Bir iş telefon numarası girin",
    },

    mobilePhone: {
        label: "Cep Telefonu Numarası",
        errMessage: "Bir iş telefon numarası girin"
    },

    address1: {
        label: "Adres",
        errMessage: "Adresinizi girin",
    },

    address2: {
        label: "Adres",
        errMessage: "Adresinizi girin",
    },

    mmmJobRole1: {
        label: "İşlev",
        errMessage: "Bir değer seçin",
        options: [
            // [Backend value, Frontend value]                
            ["Admin Assistant/Secretary", "Yönetici Asistanı/Sekreter"],
            ["Administrator", "Yönetici"],
            ["Advertising", "Reklam"],
            ["Ambulatory Care", "Ayakta Tedavi"],
            ["Anesthesiologist", "Anestezi Uzmanı"],
            ["Applicator", "Aplikatör"],
            ["Architect", "Mimar"],
            ["Assembler", "Montajcı"],
            ["Assistant Manager", "Yönetici Asistanı"],
            ["Brand Manager", "Marka Yöneticisi"],
            ["Business End User", "İşletme Son Kullanıcısı"],
            ["Carpenter", "Marangoz"],
            ["CDI Specialist/Manager", "CDI Uzmanı/Müdürü"],
            ["Chef", "Şef"],
            ["Chief Compliance Officer", "Baş Uyum Görevlisi"],
            ["Chief Executive Officer", "Baş Yönetici"],
            ["Chief Financial Officer", "Finans Direktörü"],
            ["Chief Medical Information Officer", "Tıbbi Bilgi Direktörü"],
            ["Chief Medical Officer", "Tıbbi Direktör"],
            ["Chief Network Officer", "Ağ Direktörü"],
            ["Chief Security Officer", "Güvenlik Görevlisi Şefi"],
            ["Chief Strategy Officer", "Strateji Direktörü"],
            ["Chief Technology Officer", "Teknoloji Direktörü"],
            ["City Planner", "Şehir Plancısı"],
            ["Clinical Director", "Klinik Direktörü"],
            ["Clinical Lead", "Klinik Yöneticisi"],
            ["Code Official/Bldg Inspector", "Kod Görevlisi/Bina Müfettişi"],
            ["Consultant", "Danışman"],
            ["Contract Packager", "Sözleşmeli Paketleyici"],
            ["Contractor/General Contractor", "Yüklenici/Genel Yüklenici"],
            ["Customer Service", "Müşteri Hizmetleri"],
            ["Damage Prevention Manager", "Hasar Önleme Müdürü"],
            ["Data Architect", "Veri Mimarı"],
            ["Dental Hygienist", "Diş Sağlığı Uzmanı"],
            ["Dental Nurse/Assistant", "Diş Hemşiresi/Asistanı"],
            ["Designer-Automotive", "Otomotiv Tasarımcısı"],
            ["Designer-Graphic", "Grafik Tasarımcı"],
            ["Designer-Industrial", "Endüstriyel Tasarımcı"],
            ["Designer-Materials", "Malzeme Tasarımcısı"],
            ["Designer-Product", "Ürün Tasarımcısı"],
            ["Detailer", "Detaycı"],
            ["Director", "Yönetici"],
            ["Dishwasher", "Bulaşık Makinesi"],
            ["Display Module Program Leader", "Ekran Modülü Program Lideri"],
            ["Distributor", "Distribütör"],
            ["Distributor-Sales Rep", "Distribütor-Satış Temcilcisi"],
            ["Drafter/Draftsman", "Çizimci/Teknik Ressam"],
            ["Educator/Instructor", "Eğitici/Eğitmen"],
            ["EHS Manager", "ÇSG Müdürü"],
            ["Electrician", "Elektrik teknisyeni"],
            ["Emergency Response Leader", "Acil Müdahale Lideri"],
            ["EMT/First Responder", "EMT/İlk Müdahale Çalışanı"],
            ["Endodontist", "Endodontist"],
            ["Energy Consultant", "Enerji Danışmanı"],
            ["Engineer-Chief", "Şef Mühendis"],
            ["Engineer-Civil", "İnşaat Mühendisi"],
            ["Engineer-Design", "Tasarım Mühendisi"],
            ["Engineer-Display", "Görüntü Mühendisi"],
            ["Engineer-Distribution", "Dağıtım Mühendisi"],
            ["Engineer-EHS", "ÇSG Mühendisi"],
            ["Engineer-Electrical", "Elektrik Mühendisi"],
            ["Engineer-FAA ", "FAA Mühendisi"],
            ["Engineer-Field", "Saha Mühendisi"],
            ["Engineer-Fire Protection", "Yangından Korunma Mühendisi"],
            ["Engineer-Fleet", "Filo Mühendisi"],
            ["Engineer-General", "Mühendis (Genel)"],
            ["Engineer-Maintenance ", "Bakım Mühendisi"],
            ["Engineer-Manufacturing/Fab", "İmalat/Fabrikasyon Mühendisi"],
            ["Engineer-Materials", "Malzeme Mühendisi"],
            ["Engineer-Mechanical", "Makine Mühendisi"],
            ["Engineer-Medical", "Tıp Mühendisi"],
            ["Engineer-Mining", "Maden Mühendisi"],
            ["Engineer-Network/Data Center", "Ağ/Veri Merkezi Mühendisi"],
            ["Engineer-Operations", "Operasyon Mühendisi"],
            ["Engineer-Optical", "Optik Mühendisi"],
            ["Engineer-Packaging", "Ambalaj Mühendisi"],
            ["Engineer-Power Distribution", "Güç Dağıtım Mühendisi"],
            ["Engineer-Process", "Proses Mühendisi"],
            ["Engineer-Product", "Ürün Mühendisi"],
            ["Engineer-Production", "Üretim Mühendisi"],
            ["Engineer-Quality", "Kalite Mühendisi"],
            ["Engineer-R&D", "Ar-Ge Mühendisi"],
            ["Engineer-Safety", "Güvenlik Mühendisi"],
            ["Engineer-Standards", "Standart Mühendisi"],
            ["Engineer-Structural", "Yapı Mühendisi"],
            ["Engineer-Systems", "Sistem Mühendisi"],
            ["Engineer-Traffic", "Trafik Mühendisi"],
            ["Environmental Svcs Manager", "Çevre Hizmetleri Müdürü"],
            ["Estimator", "Tahminci"],
            ["Executive", "Yönetici"],
            ["Fabricator", "İmalatçı"],
            ["Field Worker", "Saha Çalışanı"],
            ["Finance & Accounting", "Finans ve Muhasebe"],
            ["Fire Chief", "İtfaiye Şefi"],
            ["Firefighter", "İtfaiyeci"],
            ["Fleet Manager", "Filo Müdürü"],
            ["General Dentist", "Genel Diş Hekimi"],
            ["Govt Official/Rep", "Devlet Görevlisi/Temsilcisi"],
            ["Healthcare Professional", "Sağlık Çalışanı"],
            ["Home Owner", "Ev Sahibi"],
            ["Human Resources", "İnsan Kaynakları"],
            ["Industrial Hygienist", "Endüstriyel Hijyen Uzmanı"],
            ["Infection Preventionist", "Enfeksiyon Önleme Uzmanı"],
            ["Installer", "Tesisatçı"],
            ["Installer-Drywall", "Alçıpan Kurulum Uzmanı"],
            ["Installer-Electrical", "Elektrik Tesisatçısı"],
            ["Installer-HVAC", "HVAC Kurulum Uzmanı"],
            ["Installer-Insulation", "Yalıtım Kurulum Uzmanı"],
            ["Insurance Representative", "Sigorta Temsilcisi"],
            ["IT/Information Technology", "BT/Bilgi Teknolojisi"],
            ["Kitchen Manager", "Mutfak Müdürü"],
            ["Kitchen Staff Member", "Mutfak Personeli"],
            ["Laboratory Manager", "Laboratuvar Müdürü"],
            ["Laboratory Technician", "Laboratuvar Teknisyeni"],
            ["Law Enforcement", "Emniyet"],
            ["Legal", "Kanuni"],
            ["Lineman/Splicer", "Hat İşçisi/Birleştirici"],
            ["Logistics/Supply Chain", "Lojistik/Tedarik Zinciri"],
            ["Machinist/Operator", "Makinist/Operatör"],
            ["Maintenance Manager/Facilities Mgmt", "Bakım Müdürü/Tesis Yönetimi"],
            ["Manager/Supervisor", "Yönetici/Süpervizör"],
            ["Marketing", "Pazarlama"],
            ["Mason/Bricklayer", "Duvar Ustası/Duvarcı"],
            ["Mechanic", "Tamirci"],
            ["Medical Assistant", "Tıp Asistanı"],
            ["Midwife", "Ebe"],
            ["Military Officer", "Askeri Görevli"],
            ["Military Solider", "Asker"],
            ["Network Administration ", "Ağ Yönetimi "],
            ["Network Operations", "Ağ İşlemleri"],
            ["Nurse", "Hemşire"],
            ["Nursing Manager", "Bakım Müdürü"],
            ["Occupational Health Manager", "İş Sağlığı Müdürü"],
            ["Office Manager", "Ofis Yöneticisi"],
            ["Operations", "Operasyonlar"],
            ["Operations Manager", "Operasyon Müdürü"],
            ["Oral Health Therapist/Dental Therapist", "Ağız Sağlığı Terapisti/Diş Terapisti"],
            ["Oral Surgeon", "Ağız Cerrahı"],
            ["Orthodontics Nurse/Assistant", "Ortodonti Hemşiresi/Asistanı"],
            ["Orthodontist", "Ortodontist"],
            ["Paint Jobber", "Geçici Boya İşçisi"],
            ["Paint Manufacturer", "Boya Üreticisi"],
            ["Painter/Paint Professional", "Boyacı/ Boya Uzmanı"],
            ["Pediatric Dentist", "Pediatrik Diş Hekimi"],
            ["Periodontist", "Periodontist"],
            ["Pharmacist/Chemist", "Eczacı/Kimyager"],
            ["Physical Therapist", "Fizyoterapist"],
            ["Physician", "Doktor"],
            ["Physician Assistant", "Doktor Asistanı"],
            ["Physiotherapist", "Fizyoterapist"],
            ["Plant Manager", "Fabrika Müdürü"],
            ["Plumber", "Tesisatçı"],
            ["President/Owner", "Başkan/Sahip"],
            ["Press Room Operator", "Basın Odası Operatörü"],
            ["Print Room Manager", "Baskı Odası Müdürü"],
            ["Product Manager", "Ürün Yöneticisi"],
            ["Product/Design Developer", "Ürün/Tasarım Geliştiricisi"],
            ["Production Employee", "Üretim Çalışanı"],
            ["Production Manager", "Üretim Yöneticisi"],
            ["Project Manager", "Proje Müdürü"],
            ["Property Manager", "Gayrimenkul Yöneticisi"],
            ["Prosthodontist", "Protez Uzmanı"],
            ["Purchasing/Procurement/Buyer", "Satın Alma/Tedarik/Alıcı"],
            ["Quality Assurance", "Kalite Güvencesi"],
            ["Radiologist", "Radyolog"],
            ["Realtor", "Emlakçı"],
            ["Research & Development", "Araştırma ve Geliştirme"],
            ["Revenue Manager", "Gelir Yöneticisi"],
            ["Safety Consultant", "Güvenlik Danışmanı"],
            ["Safety Manager", "Güvenlik Müdürü"],
            ["Sales", "Satış"],
            ["Sanitation Manager", "Sanitasyon Müdürü"],
            ["Scientist", "Bilim İnsanı"],
            ["Security", "Güvenlik"],
            ["Service Adviser", "Hizmet Danışmanı"],
            ["Specifier", "Belirleyici"],
            ["Stay At Home Parent", "Evden Çalışan Ebeveyn"],
            ["Store Clerk/Counter Employee", "Mağaza Görevlisi/Kasa Çalışanı"],
            ["Store Owner/Shop Owner ", "Mağaza Sahibi/Dükkân Sahibi "],
            ["Student", "Öğrenci"],
            ["Surgeon", "Cerrah"],
            ["Technical Manager", "Teknik Müdür"],
            ["Technical Services", "Teknik Hizmetler"],
            ["Technician-Body Repair/Bodyman", "Kaporta Onarım Teknisyeni/Kaporta Ustası"],
            ["Technician-Data Center", "Veri Merkezi Teknisyeni"],
            ["Technician-Field", "Saha Teknisyeni"],
            ["Technician-Fire Supression", "Yangın Söndürme Teknisyeni"],
            ["Technician-General", "Teknisyen (Genel)"],
            ["Technician-HVAC", "HVAC Teknisyeni"],
            ["Technician-Mechanical", "Mekanik Teknisyeni"],
            ["Technician-Service", "Servis Teknisyeni"],
            ["Technology/Innovation Manager", "Teknoloji/İnovasyon Müdürü"],
            ["Tool Crib Manager", "Takım Deposu Müdürü"],
            ["Touch Display Module Program Leader", "Dokunmatik Ekran Modülü Program Lideri"],
            ["Trainer/Training", "Eğitmen/Eğitim"],
            ["Treatment Coordinator", "Tedavi Koordinatörü"],
            ["Veterinarian", "Veteriner Hekim"],
            ["Warehouse Worker", "Depo Çalışanı"],
            ["Welder", "Kaynakçı"],
            ["Wholesaler", "Toptancı"],
            ["Other", "Diğer"],

        ]

    },

    jr_other: {
        label: "Diğer İşlev",
        errMessage: "İş pozisyonunuzu girin ",
    },

    mmmIndustry1: {
        label: "Sektör",
        errMessage: "Bir değer seçin",
        options:
            [
                // [Backend value, Frontend value]                
                ["Transp-Aerospace Mfg", "Hava-Uzay İmalatı"],
                ["Transp-Aerospace MRO", "Hava-Uzay Bakım, Onarım ve Operasyonları"],
                ["Transp-Aerospace Operators", "Hava-Uzay Operatörleri"],
                ["Industrial-Agriculture & Forestry", "Tarım ve Ormancılık"],
                ["Healthcare-Ambulatory Surgery Center", "Günübirlik Cerrahi Merkezi"],
                ["Industrial-Appliance Mfg", "Alet İmalatı"],
                ["Industrial-Arch & Structural Metals Mfg", "Kemer ve Yapısal Metal İmalatı"],
                ["Construction-Architectural Services", "Mimari Hizmetler"],
                ["Industrial-Asphalt & Roofing Material Mfg", "Asfalt ve Çatı Malzemeleri İmalatı"],
                ["Retail-Auto Parts & Gasoline", "Otomobil Parçaları ve Benzin Perakende Hizmetleri"],
                ["Retail-Automobile Dealerships", "Otomobil Bayilikleri"],
                ["Transp-Automotive Mfg", "Otomotiv İmalatı"],
                ["Transp-Automotive Restyling", "Otomotiv Yeniden Şekillendirme"],
                ["Industrial-Bearings & Gears Mfg", "Rulmanlar ve Dişli İmalatı"],
                ["Retail-Books & Stationary", "Kitap ve Kırtasiye Perakende Hizmetleri"],
                ["Industrial-Builders Hardware Mfg", "Bina Donanımı İmalatı"],
                ["Construction-Bldg Contractor Svcs", "İnşaat Yüklenici Hizmetleri"],
                ["Transp-Bus Mfg", "Otobüs İmalatı"],
                ["Transp-Car Care Centers", "Araç Bakım Merkezleri"],
                ["Industrial-Chemical Mfg", "Kimyasal Madde İmalatı"],
                ["Transp-Collison Repair", "Kaza Tamiri"],
                ["Transp-Comm & Specialty Veh Maint", "Ticari ve Özel Araç Bakımı"],
                ["Construction-Commercial", "Ticari İnşaat"],
                ["Transp-Comm Veh Mfg", "Ticari Araç İmalatı"],
                ["Comms-Telecommunications", "İletişim"],
                ["Industrial-Composites Mfg", "Kompozit İmalatı"],
                ["Electronics-Consumer Electronics", "Tüketici Elektroniği"],
                ["Retail-Consumer Electronics", "Tüketici Elektroniği Perakende Hizmetleri"],
                ["Industrial-Cutting Tool Mfg", "Kesme Takımı İmalatı"],
                ["Comms-Data Center", "Veri Merkezi"],
                ["Defense/Military", "Savunma/Askeri"],
                ["Industrial-Dental Product Mfg", "Diş Ürünleri İmalatı"],
                ["Healthcare-Dentists", "Diş Hekimleri"],
                ["Distribution", "Dağıtım"],
                ["eCommerce/Fulfillment", "e-Ticaret/Sipariş İşleme"],
                ["Education-Colleges & Universities", "Eğitim - Kolejler ve Üniversiteler"],
                ["Industrial-Electrical Equip Mfg", "Elektrikli Ekipman İmalatı"],
                ["Industrial-Elevator & Escalator Mfg", "Asansör/Yürüyen Merdiven İmalatı"],
                ["Public Safety-Emerg Preparedness", "Acil Durum Hazırlığı"],
                ["Finance & Insurance", "Finans ve Sigorta"],
                ["Public Safety-Fire & Rescue Services", "Yangın ve Kurtarma Hizmetleri"],
                ["Industrial-Fire Protection & Suppr", "Yangından Koruma ve Yangın Söndürme"],
                ["Retail-Focused Specialty", "Odaklı Özel Perakende Hizmetleri"],
                ["Industrial-Food & Beverage Mfg", "Gıda ve İçecek İmalatı"],
                ["Retail-Food & Beverage", "Yiyecek ve İçecek Perakende Hizmetleri"],
                ["Food Service", "Yemek Hizmeti"],
                ["Industrial-Forging & Stamping", "Dövme ve Damgalama"],
                ["Industrial-Furniture Mfg", "Mobilya İmalatı"],
                ["Government", "Devlet"],
                ["Healthcare-Govt Health Agencies", "Devlet Sağlık Ajansları"],
                ["Graphics & Signage", "Grafikler ve İşaretler"],
                ["Industrial-Hand Tool Mfg", "El Aletleri İmalatı"],
                ["Healthcare-Health Insurers", "Sağlık Sigortacıları"],
                ["Healthcare-Home Care", "Evde Bakım"],
                ["Retail-Home Impr/Hardware", "Ev Dekorasyonu/Hırdavatçılar"],
                ["Hospitality", "Konaklama"],
                ["Healthcare-Hospitals", "Hastaneler"],
                ["Industrial-HVAC Equip Mfg", "HVAC Ekipmanları İmalatı"],
                ["Industrial-Indust Machinery & Equip Mfg", "Endüstriyel Makine ve Ekipman İmalatı"],
                ["Janitorial Services", "Temizlik Hizmetleri"],
                ["Landscape Services", "Peyzaj Hizmetleri"],
                ["Public Safety-Law Enforcement", "Emniyet"],
                ["Transp-Marine Mfg & Maint", "Denizcilik İmalatı ve Bakımı"],
                ["Retail-Mass Retail/Warehouse", "Toplu Perakende Hizmetleri/Depo"],
                ["Healthcare-Medical & Diag Labs", "Tıbbi Laboratuvarlar & Tanı Laboratuvarları"],
                ["Industrial-Medical Devices Mfg", "Tıbbi Cihaz İmalatı"],
                ["Industrial-Mining", "Madencilik"],
                ["Construction-Modular", "Modüler İnşaat"],
                ["Retail-Office Supply", "Ofis Malzemeleri Mağazaları"],
                ["Industrial-Oil & Gas", "Petrol ve Gaz"],
                ["Healthcare-Orthodontists", "Ortodontistler"],
                ["Industrial-Other Fabr Metals Mfg", "Diğer Fabrikasyon Metal İmalatı"],
                ["Healthcare-Other Health Practitioners", "Diğer Sağlık Çalışanları"],
                ["Industrial-Outdoor Sports/Equip Mfg", "Doğa Sporları/Ekipman İmalatı"],
                ["Healthcare-Outpatient Clinics", "Poliklinikler"],
                ["Industrial-Paints & Coatings Mfg", "Boya ve Kaplama İmalatı"],
                ["Industrial-Paper & Pulp Mfg", "Kağıt ve Kağıt Hamuru İmalatı"],
                ["Industrial-Pharmaceutical Mfg", "İlaç İmalatı"],
                ["Retail-Pharmacies & Drug Stores", "Eczaneler ve İlaç Mağazaları"],
                ["Industrial-Plastics Mfg", "Plastik İmalatı"],
                ["Utilities-Power Dist & Transmission", "Güç Dağıtımı ve İletimi"],
                ["Utilities-Power Generation", "Güç Üretimi"],
                ["Industrial-Power Tool Mfg", "Elektrikli Alet İmalatı"],
                ["Healthcare-Primary Care", "Birincil Bakım"],
                ["Industrial-Primary Metals Mfg", "Birincil Metal İmalatı"],
                ["Industrial-Printing", "Baskı"],
                ["Transp-Rail Fleet Operators", "Demiryolu Filosu Operatörleri"],
                ["Transp-Railcar Mfg & Maint", "Vagon/Lokomotif İmalatı ve Bakımı"],
                ["Real Estate", "Gayrimenkul"],
                ["Construction-Residential", "Konut İnşaatı"],
                ["Transp-Road Fleet Operators", "Demiryolu Filosu Operatörleri"],
                ["Industrial-Rubber Mfg", "Kauçuk İmalatı"],
                ["Electronics-Semicon & Circuit Boards", "Yarı İletkenler ve Devre Kartları"],
                ["Transp-Ship Building & Maint", "Gemi İnşa ve Bakımı"],
                ["Industrial-Sign Mfg", "Tabela İmalatı"],
                ["Healthcare-SNF/Residential Care", "Nitelikli Bakım Tesisi/Evde Bakım"],
                ["Transp-Specialty Veh Mfg", "Özel Araç İmalatı"],
                ["Industrial-Textiles Mfg", "Tekstil İmalatı"],
                ["Transp-Toll Authority", "Geçiş Ücreti Otoritesi"],
                ["Construction-Transp Infrastructure", "Ulaşım Altyapısı"],
                ["Industrial-Turbine & Engine Mfg", "Türbin ve Motor İmalatı"],
                ["Transp-Two-Wheel Veh Mfg & Maint", "İki Tekerlekli Araç İmalatı ve Bakımı"],
                ["Construction-Utilities Infrastructure", "Kamu Hizmetleri Altyapısı"],
                ["Transp-Vehicle Parts Mfg", "Araç Parça İmalatı"],
                ["Transp-Vehicle Registration", "Araç Tescili"],
                ["Utilities-Water & Sewage", "Su ve Kanalizasyon Tesisleri"],
                ["Transp-Water Fleet Operators", "Su Filosu Operatörleri"],
                ["Industrial-Window & Door Mfg", "Pencere ve Kapı İmalatı"],
                ["Industrial-Woodworking", "Ağaç işleri"],
                ["Other", "Diğer"],
            ],
            EMSD: {
                label: "Sektör", // Original: Industry/ Market Segment
            }


    },

    salesRequest: {
        label: "3M temsilcisi ile konuşmak istiyorum",
        errMessage: "Bir değer seçin",
        value: "Yes",
        options: [
            // [Backend value, Frontend value]    
            ["Yes", "Evet"],
            ["No", "Hayır"],
        ],

        ASD: {           
                        
            TMC: {
                label: "Taşımacılık Çözümleri alanında bir 3M Uzmanı ile görüşmek istiyorum",
            }
        }

    },

    custEnq: {
        label: "Yaşadığınız Zorluk veya Uygulamanız Nedir?",
        errMessage: "Yaşadığınız Zorluk veya Uygulamanız Nedir?",
        ASD: {
            TMC: {
                label: 'Sizi zorlayan veya sizde sıkıntı yaratan konu nedir?',
            }
        }
    },

    selDist: {
        label: "Distribütörünüz kim?",
        errMessage: "Bir Distribütör seçin",
        options: [
            // [Backend value, Frontend value]    
            ["Option 1", "Option 1"],
            ["Option 2", "Option 2"],
            ["Option 3", "Option 3"],
        ]

    },

    country: {
        label: "Ülke",
        errMessage: "Bir ülke girin",
        options: [
            // [Backend value, Frontend value]    

            ["Afghanistan", "Afganistan"],
            ["Aland Islands", "Aland Adaları"],
            ["Albania", "Arnavutluk"],
            ["Algeria", "Cezayir"],
            ["Andorra", "Andorra"],
            ["Angola", "Angola"],
            ["Anguilla", "Anguilla"],
            ["Antarctica", "Antarktika"],
            ["Antigua and Barbuda", "Antigua ve Barbuda"],
            ["Argentina", "Arjantin"],
            ["Armenia", "Ermenistan"],
            ["Aruba", "Aruba"],
            ["Australia", "Avustralya"],
            ["Austria", "Avusturya"],
            ["Azerbaijan", "Azerbaycan"],
            ["Bahamas", "Bahamalar"],
            ["Bahrain", "Bahreyn"],
            ["Bangladesh", "Bangladeş"],
            ["Barbados", "Barbados"],
            ["Belarus", "Beyaz Rusya"],
            ["Belgium", "Belçika"],
            ["Belize", "Belize"],
            ["Benin", "Benin"],
            ["Bermuda", "Bermuda"],
            ["Bhutan", "Butan"],
            ["Bolivia", "Bolivya"],
            ["Bonaire, Sint Eustatius and Saba", "Bonaire, Sint Eustatius ve Saba"],
            ["Bosnia and Herzegovina", "Bosna Hersek"],
            ["Botswana", "Botsvana"],
            ["Bouvet Island", "Bouvet Adası"],
            ["Brazil", "Brezilya"],
            ["British Indian Ocean Territory", "İngiliz Hint Okyanusu Bölgesi"],
            ["Brunei Darussalam", "Brunei Sultanlığı"],
            ["Bulgaria", "Bulgaristan"],
            ["Burkina Faso", "Burkina Faso"],
            ["Burundi", "Burundi"],
            ["Cambodia", "Kamboçya"],
            ["Cameroon", "Kamerun"],
            ["Canada", "Kanada"],
            ["Cape Verde", "Cape Verde"],
            ["Cayman Islands", "Cayman Adaları"],
            ["Central African Republic", "Orta Afrika Cumhuriyeti"],
            ["Chad", "Çad"],
            ["Chile", "Şili"],
            ["China", "Çin"],
            ["Christmas Island", "Christmas Adası"],
            ["Cocos (Keeling) Islands", "Cocos (Keyling) Adaları"],
            ["Colombia", "Kolombiya"],
            ["Comoros", "Komorlar"],
            ["Congo", "Kongo"],
            ["Congo, the Democratic Republic of the", "Kongo Demokratik Cumhuriyeti"],
            ["Cook Islands", "Cook Adaları"],
            ["Costa Rica", "Kosta Rika"],
            ["Croatia", "Hırvatistan"],
            ["Cuba", "Küba"],
            ["Cura&ccedil;ao", "Curaçao"],
            ["Cyprus", "Kıbrıs"],
            ["Czech Republic", "Çek Cumhuriyeti"],
            ["Denmark", "Danimarka"],
            ["Djibouti", "Cibuti"],
            ["Dominica", "Dominika"],
            ["Dominican Republic", "Dominik Cumhuriyeti"],
            ["Dutch Antilles", "Hollanda Antilleri"],
            ["Ecuador", "Ekvador"],
            ["Egypt", "Mısır"],
            ["El El Salvador", "El Salvador"],
            ["Equatorial Guinea", "Ekvator Ginesi"],
            ["Eritrea", "Eritre"],
            ["Estonia", "Estonya"],
            ["Ethiopia", "Etiyopya"],
            ["Falkland Islands (Malvinas)", "Falkland Adaları (Malvinas)"],
            ["Faroe Islands", "Faroe Adaları"],
            ["Fiji", "Fiji"],
            ["Finland", "Finlandiya"],
            ["France", "Fransa"],
            ["French Guiana", "Fransız Guyanası"],
            ["French Polynesia", "Fransız Polinezyası"],
            ["French Southern Territories", "Fransız Güney Toprakları"],
            ["Gabon", "Gabon"],
            ["Gambia", "Gambiya"],
            ["Georgia", "Gürcistan"],
            ["Germany", "Almanya"],
            ["Ghana", "Gana"],
            ["Gibraltar", "Cebelitarık"],
            ["Greece", "Yunanistan"],
            ["Greenland", "Grönland"],
            ["Grenada", "Grenada"],
            ["Guadeloupe", "Guadeloupe"],
            ["Guam", "Guam"],
            ["Guatemala", "Guatemala"],
            ["Guernsey", "Guernsey"],
            ["Guinea", "Gine"],
            ["Guinea-Bissau", "Gine-Bissau"],
            ["Guyana", "Guyana"],
            ["Haiti", "Haiti"],
            ["Heard Island and McDonald Islands", "Heard Adası ve McDonald Adaları"],
            ["Holy See (Vatican City State)", "Kutsal Makam (Vatikan Şehir Devleti)"],
            ["Honduras", "Honduras"],
            ["Hong Kong", "Hong Kong"],
            ["Hungary", "Macaristan"],
            ["Iceland", "İzlanda"],
            ["India", "Hindistan"],
            ["Indonesia", "Endonezya"],
            ["Iran, Islamic Republic of", "İran İslam Cumhuriyeti"],
            ["Iraq", "Irak"],
            ["Ireland", "İrlanda"],
            ["Isle of Man", "Man Adası"],
            ["Israel", "İsrail"],
            ["Italy", "İtalya"],
            ["Ivory Coast", "Fildişi Sahili"],
            ["Jamaica", "Jamaika"],
            ["Japan", "Japonya"],
            ["Jersey", "Jersey"],
            ["Jordan", "Ürdün"],
            ["Kazakhstan", "Kazakistan"],
            ["Kenya", "Kenya"],
            ["Kiribati", "Kiribati"],
            ["Korea - Republic of", "Kore Cumhuriyeti"],
            ["Kosovo", "Kosova"],
            ["Kuwait", "Kuveyt"],
            ["Kyrgyzstan", "Kırgızistan"],
            ["Lao People's Democratic Republic", "Lao Demokratik Halk Cumhuriyeti"],
            ["Latvia", "Letonya"],
            ["Lebanon", "Lübnan"],
            ["Lesotho", "Lesotho"],
            ["Liberia", "Liberya"],
            ["Libyan Arab Jamahiriya", "Libya Arap Cumhuriyeti"],
            ["Liechtenstein", "Lihtenştayn"],
            ["Lithuania", "Litvanya"],
            ["Luxembourg", "Lüksemburg"],
            ["Macao", "Makao"],
            ["Macedonia, the former Yugoslav Republic of", "Makedonya Eski Yugoslav Cumhuriyeti"],
            ["Madagascar", "Madagaskar"],
            ["Malawi", "Malavi"],
            ["Malaysia", "Malezya"],
            ["Maldives", "Maldivler"],
            ["Mali", "Mali"],
            ["Malta", "Malta"],
            ["Marshall Islands", "Marshall Adaları"],
            ["Martinique", "Martinik"],
            ["Mauritania", "Moritanya"],
            ["Mauritius", "Mauritius"],
            ["Mayotte", "Mayotte"],
            ["Mexico", "Meksika"],
            ["Micronesia", "Mikronezya"],
            ["Moldova, Republic of", "Moldova Cumhuriyeti"],
            ["Monaco", "Monako"],
            ["Mongolia", "Moğolistan"],
            ["Montenegro", "Karadağ"],
            ["Montserrat", "Montserrat"],
            ["Morocco", "Fas"],
            ["Mozambique", "Mozambik"],
            ["Myanmar", "Burma"],
            ["Namibia", "Namibya"],
            ["Nauru", "Nauru"],
            ["Nepal", "Nepal"],
            ["Turkey", "Türkiye"],
            ["Netherlands", "Hollanda"],
            ["New Caledonia", "Yeni Kaledonya"],
            ["New Zealand", "Yeni Zelanda"],
            ["Nicaragua", "Nikaragua"],
            ["Niger", "Nijer"],
            ["Nigeria", "Nijerya"],
            ["Niue", "Niue"],
            ["Norfolk Island", "Norfolk Adası"],
            ["North Korea", "Kuzey Kore"],
            ["Northern Mariana Islands", "Kuzey Mariana Adaları"],
            ["Norway", "Norveç"],
            ["Oman", "Umman"],
            ["Pakistan", "Pakistan"],
            ["Palau", "Palau"],
            ["Palestine", "Filistin"],
            ["Panama", "Panama"],
            ["Papua New Guinea", "Papua Yeni Gine"],
            ["Paraguay", "Paraguay"],
            ["Peru", "Peru"],
            ["Philippines", "Filipinler"],
            ["Pitcairn", "Pitcairn"],
            ["Poland", "Polonya"],
            ["Portugal", "Portekiz"],
            ["Puerto Rico", "Porto Riko"],
            ["Qatar", "Katar"],
            ["Reunion", "Reunion"],
            ["Romania", "Romanya"],
            ["Russian Federation", "Rusya Federasyonu"],
            ["Rwanda", "Ruanda"],
            ["Saint Barth&eacute;lemy", "Saint Barthelemy"],
            ["Saint Helena, Ascension and Tristan da Cunha", "Saint Helena, Ascension ve Tristan da Cunha"],
            ["Saint Kitts and Nevis", "Saint Kitts ve Nevis"],
            ["Saint Lucia", "Saint Lucia"],
            ["Saint Martin", "Saint Martin"],
            ["Saint Pierre and Miquelon", "Saint Pierre ve Miquelon"],
            ["Saint Vincent and the Grenadines", "Saint Vincent ve Grenadinler"],
            ["Samoa", "Samoa"],
            ["Samoa, American", "Amerikan Samoası"],
            ["San Marino", "San Marino"],
            ["Sao Tome and Principe", "Sao Tome ve Principe"],
            ["Saudi Arabia", "Suudi Arabistan"],
            ["Senegal", "Senegal"],
            ["Serbia", "Sırbistan"],
            ["Seychelles", "Seyşeller"],
            ["Sierra Leone", "Sierra Leone"],
            ["Singapore", "Singapur"],
            ["Sint Maarten", "Sint Maarten"],
            ["Slovakia", "Slovakya"],
            ["Slovenia", "Slovenya"],
            ["Solomon Islands", "Solomon Adaları"],
            ["Somalia", "Somali"],
            ["South Africa", "Güney Afrika"],
            ["South Georgia and the South Sandwich Islands", "Güney Georgia ve Güney Sandwich Adaları"],
            ["South Sudan", "Güney Sudan"],
            ["Spain", "İspanya"],
            ["Sri Lanka", "Sri Lanka"],
            ["Sudan", "Sudan"],
            ["Suriname", "Surinam"],
            ["Svalbard and Jan Mayen", "Svalbard ve Jan Mayen"],
            ["Swaziland", "Svaziland"],
            ["Sweden", "İsveç"],
            ["Switzerland", "İsviçre"],
            ["Syrian Arab Republic", "Suriye Arap Cumhuriyeti"],
            ["Taiwan", "Tayvan"],
            ["Tajikistan", "Tacikistan"],
            ["Tanzania, United Republic of", "Tanzanya Birleşik Cumhuriyeti"],
            ["Thailand", "Tayland"],
            ["Timor-Leste", "Timor-Leste"],
            ["Togo", "Togo"],
            ["Tokelau", "Tokelau"],
            ["Tonga", "Tonga"],
            ["Trinidad and Tobago", "Trinidad ve Tobago"],
            ["Tunisia", "Tunus"],
            ["Turkmenistan", "Türkmenistan"],
            ["Turks and Caicos Islands", "Turks ve Caicos Adaları"],
            ["Tuvalu", "Tuvalu"],
            ["Uganda", "Uganda"],
            ["Ukraine", "Ukrayna"],
            ["United Arab Emirates", "Birleşik Arap Emirlikleri"],
            ["United Kingdom", "Birleşik Krallık"],
            ["United States Minor Outlying Islands", "Amerika Birleşik Devletleri Küçük Dış Adaları"],
            ["United States", "Amerika Birleşik Devletleri"],
            ["Uruguay", "Uruguay"],
            ["Uzbekistan", "Özbekistan"],
            ["Vanuatu", "Vanuatu"],
            ["Venezuela", "Venezuela"],
            ["Vietnam", "Vietnam"],
            ["Virgin Islands, British", "Britanya Virjin Adaları"],
            ["Virgin Islands, US", "Virjin Adaları"],
            ["Wallis and Futuna", "Wallis ve Futuna"],
            ["Western Sahara", "Batı Sahra"],
            ["Yemen", "Yemen"],
            ["Zambia", "Zambiya"],
            ["Zimbabwe", "Zimbabve"],


        ]
    },

    elqGlobalLanguage: {
        label: "Dil",
        errMessage: "Dilinizi girin",
    },

    stateProv: {
        label: "Ilçe",
        errMessage: "Ülke seçiniz",
    },

    sample: {
        type: "select",
        label: "Please choose at least one product of interest",
        errMessage: "Bir örnek seçin",
        options: [
            // [Backend value, Frontend value]   
            ['First', 'First'],
            ['Second', 'Second'],
            ['Third', 'Third'],               
        ]
    },

    /** 
     * Specific fields for Division / SMP below
     * 1) EMSD
     * 2) ASD
    */

    // 1) Specific fields for EMSD only
    EMSD: {
        appHeader: {
            type: "header",
            label: "Başvuru Amacı",
            subLabel: "",
        },
        app1: {
            type: "checkbox",
            label: "Elektronik Yapıştırma ",
            errMessage: "Bir değer seçin",
            value: "Electronic Bonding"
        },
        app2: {
            type: "checkbox",
            label: "Kalkanlama EMI",
            errMessage: "Bir değer seçin",
            value: "Shielding EMI/\EMC/\Absorber"
        },
        app3: {
            type: "checkbox",
            label: "Yangın Koruması",
            errMessage: "Bir değer seçin",
            value: "Fire Protection"
        },
        app4: {
            type: "checkbox",
            label: "Daldırma soğutma /\ ısı transferi",
            errMessage: "Bir değer seçin",
            value: "Immersion cooling /\ heat transfer"
        },
        app5: {
            type: "checkbox",
            label: "Yalıtım gazları",
            errMessage: "Bir değer seçin",
            value: "Insulating gases"
        },
        app6: {
            type: "checkbox",
            label: "Ara bağlantı /\ veri aktarımı",
            errMessage: "Bir değer seçin",
            value: "Factory Automation /\ Interconnect /\ data transfer"
        },
        app7: {
            type: "checkbox",
            label: "Koruma yastığı ve gürültü azaltma",
            errMessage: "Bir değer seçin",
            value: "Protection cushioning and noise dampening"
        },
        app8: {
            type: "checkbox",
            label: "Koruyucu kaplama",
            errMessage: "Bir değer seçin",
            value: "Protective coating"
        },
        app9: {
            type: "checkbox",
            label: "Köpük üfleme katkı maddeleri",
            errMessage: "Bir değer seçin",
            value: "Foam blowing additives /\ formulation additives"
        },
        app10: {
            type: "checkbox",
            label: "Yarı iletken imalat veya işleme",
            errMessage: "Bir değer seçin",
            value: "Semiconductor manufacturing or processing"
        },
        app11: {
            type: "checkbox",
            label: "Solvent temizleme ve buharla yağ giderme",
            errMessage: "Bir değer seçin",
            value: "Solvent cleaning and vapour degreasing"
        },
        app12: {
            type: "checkbox",
            label: "Termal Arayüz Malzemeleri (TIM)",
            errMessage: "Bir değer seçin",
            value: "Thermal Interface Materials"
        },
        app13: {
            type: "checkbox",
            label: "Diğer",
            errMessage: "Bir değer seçin",
            value: "Other"
        },

        EMSD_cust_type: {
            type: "select",
            label: "Müşteri Türü",
            errMessage: "Bir değer seçin",
            options: [
                ['VAR', 'VAR /\ Dönüştürücüler'],
                ['Consultancy', 'Danışman'],
                ['Channel Partner /\ Distributor', 'Kanal Ortağı /\ Distribütör'],
                ['End User', 'Son Kullanıcı'],
                ['Government', 'Government'],
                ['OEM', 'OEM'],
                ['Tier', 'Tier'],
            ]
            },

        EMSD_app_purp_other: {
            type: "text",
            label: "Diğer Başvuru Amacı",
            errMessage: "Bir değer seçin",
        },

        EMSD_jr_other: {
            type: "text",
            label: "Diğer İşlev",
            errMessage: "İş pozisyonunuzu girin ",
        },
    },

   // 2) Specific fields for ASD only

   ASD: {
    processImprovement: {
        type: "select",
        label: "Aşındırıcı işlemlerinizle ilgili en çok neyi geliştirmek istersiniz?",
        errMessage: "Bir değer seçin",
        options: [
            // [Backend value, Frontend value]   
            ['Process speed', 'Proses hızı'],
            ['Safety hazard mitigation', 'Güvenlik tehlikelerinin azaltılması'],
            ['Surface finishing consistency', 'Yüzey finisaj tutarlılığı'],
            ['Abrasive durability', 'Aşındırıcı dayanıklılığı'],
        ]
    },
    
    NumberofOperators: {
        type: "select",
        label: "Aşındırıcı Kullanıcılarının Sayısı",
        errMessage: "Bir değer seçin",
        options: [
            // [Backend value, Frontend value]   
            ['0-1', '0-1'],
            ['2-5', '2-5'],
            ['6-11', '6-11'],
            ['11+', '11+'],
        ]
    },

    
    TMC_numberOfOperators: {
        type: "select",
        label: "Operatör Sayısı",
        errMessage: "Bir değer seçin",
        options: [
            // [Backend value, Frontend value]   
            ['0-5', '0-5'],
            ['6-20', '6-20'],
            ['>20', '>20'],
        ]           
    },

    TMC_comp_type: {
        type: "select",
        label: "Şirket Türü",
        errMessage: "Bir değer seçin",
        options: [
            // [Backend value, Frontend value]
            ['End User', 'Manufacturing Company or Tier'],
            ['Distributor', 'Distributor/Converter'],
            ['Consumer', 'Personal Consumer'],
        ]
    },

    TMC_proc_type: {
        type: "select",
        label: "Proses Tipi",
        errMessage: "Bir değer seçin",
        options: [
            // [Backend value, Frontend value]   
            ['Manual', 'El ile Çalışma'],
            ['Robotic', 'Robotla Çalışma'],
            ['Other', 'Diğer'],
        ]
    },

    TMC_app_type: {
        type: "select",
        label: "Uygulama Türü",
        errMessage: "Bir değer seçin",
        options: [
            // [Backend value, Frontend value]   
            ['Cutting, grinding, Weld removal', 'Kesme, taşlama, Kaynak temizleme'],
            ['Deburring', 'Çapak alma'],
            ['Sanding', 'Kumlama'],
            ['Finishing, polishing, cleaning', 'Finisaj, polisaj, temizlik,'],
            ['Coating/Spraying', 'Kaplama/Püskürtme'],
            ['Masking/Protecting', 'Maskeleme/Koruma'],
            ['Bonding & Assembly', 'Yapıştırma ve Montaj'],
            ['Safety Equipments', 'Güvenlik Ekipmanları'],
            ['Other', 'Diğer'],
        ]
    },

    TMC_substrate: {
        type: "select",
        label: "Yüzey",
        errMessage: "Bir değer seçin",
        options: [
            // [Backend value, Frontend value]   
            ['Mild Steel', 'Düşük Karbonlu Çelik'],
            ['Stainless Steel', 'Paslanmaz Çelik'],
            ['Aluminium', 'Alüminyum'],
            ['Pastic & Composites', 'Plastik ve Kompozitler'],
            ['Glass', 'Cam'],
            ['Wood', 'Ahşap'],
            ['Other', 'Diğer'],
        ]
    },       

    optInHeader: {
        type: "header",
        label: "En son 3M aşındırıcı ürün gelişmelerinden ve diğer haberlerden haberdar olmak için abone olun",            
    },
    
},

}